DEF NUM_PLAYER_NAMES EQU 3

IF DEF(_RED)
DEF PLAYERNAME1 EQUS "ROJO"
DEF PLAYERNAME2 EQUS "ASH"
DEF PLAYERNAME3 EQUS "JAIME"

DEF RIVALNAME1 EQUS "AZUL"
DEF RIVALNAME2 EQUS "GARY"
DEF RIVALNAME3 EQUS "JUAN"
ENDC

IF DEF(_BLUE)
DEF PLAYERNAME1 EQUS "AZUL"
DEF PLAYERNAME2 EQUS "GARY"
DEF PLAYERNAME3 EQUS "JUAN"

DEF RIVALNAME1 EQUS "ROJO"
DEF RIVALNAME2 EQUS "ASH"
DEF RIVALNAME3 EQUS "JAIME"
ENDC
