; These are all the asm constants needed to make the vc patches.

EXPORT DEF A_CHAR EQU 'A'
EXPORT DEF B_CHAR EQU 'B'
EXPORT DEF C_CHAR EQU 'C'
EXPORT DEF D_CHAR EQU 'D'
EXPORT DEF E_CHAR EQU 'E'
EXPORT DEF F_CHAR EQU 'F'
EXPORT DEF G_CHAR EQU 'G'
EXPORT DEF H_CHAR EQU 'H'
EXPORT DEF I_CHAR EQU 'I'
EXPORT DEF K_CHAR EQU 'K'
EXPORT DEF L_CHAR EQU 'L'
EXPORT DEF M_CHAR EQU 'M'
EXPORT DEF N_CHAR EQU 'N'
EXPORT DEF O_CHAR EQU 'O'
EXPORT DEF P_CHAR EQU 'P'
EXPORT DEF R_CHAR EQU 'R'
EXPORT DEF S_CHAR EQU 'S'
EXPORT DEF T_CHAR EQU 'T'
EXPORT DEF U_CHAR EQU 'U'
EXPORT DEF V_CHAR EQU 'V'
EXPORT DEF W_CHAR EQU 'W'
EXPORT DEF X_CHAR EQU 'X'
EXPORT DEF Y_CHAR EQU 'Y'
EXPORT DEF Z_CHAR EQU 'Z'
EXPORT DEF SPACE  EQU ' '
EXPORT DEF I_ACUT EQU 'Í'
EXPORT DEF TERMIN EQU '@'

EXPORT BLIZZARD
EXPORT BUBBLEBEAM
EXPORT CONFUSION
EXPORT DREAM_EATER
EXPORT EXPLOSION
EXPORT GUILLOTINE
EXPORT HAZE
EXPORT HYPER_BEAM
EXPORT MEGA_KICK
EXPORT MEGA_PUNCH
EXPORT PSYCHIC_M
EXPORT REFLECT
EXPORT ROCK_SLIDE
EXPORT SELFDESTRUCT
EXPORT SPORE
EXPORT THUNDERBOLT
